const baseColors = [
  "red", "blue", "green", "yellow", "purple",
  "orange", "pink", "cyan", "brown", "gold",
  "lime", "magenta", "teal", "coral", "navy",
  "crimson", "turquoise", "violet", "salmon", "khaki",
  "indigo", "maroon", "olive", "plum", "sienna",
  "aqua", "beige", "chocolate", "tomato", "orchid",
];

const countries = [
  "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg",
  "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Germany.svg",
  "https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg",
  "https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg",
  "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg",
  "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg",
  "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg",
  "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg",
  "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg",
  "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg",
  "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg",
  "https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg",
  "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg",
  "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg",
  "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/1280px-Flag_of_Senegal.svg.png",
  "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg",
  "https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Syria_%282025-%29.svg",
  "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg",
  "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg",
  "https://upload.wikimedia.org/wikipedia/commons/b/be/Flag_of_Iran_%28official%29.svg",
  "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg",
  "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
  "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg",
  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/1280px-Flag_of_Qatar.svg.png",
  "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYqvuWUdR3ikEgHxkLxGP96g_2S0d-ktDeAl2Bh70ygUSisprH_xHNCkKyjbyK&s=10",
  "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg",
  "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg",
  "https://upload.wikimedia.org/wikipedia/commons/d/df/Flag_of_Peru_%28state%29.svg",
  "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg",
  "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg",
  "https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Cyprus_%28bordered%29.svg",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS65BGqps17Okb57yOFnDE1XLzW9XokkSXraPsC7N3vXASCeYRWCGYeLq6BXiY&s=10",
  "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/1280px-Flag_of_the_Dominican_Republic.svg.png",
  "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg",
  "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg",
];

const soccerTeams = [
  "https://upload.wikimedia.org/wikipedia/he/a/a1/Man_Utd_FC_.svg",
  "https://upload.wikimedia.org/wikipedia/he/b/bc/MaccabiNetanyaNewlogo2021.png",
  "https://upload.wikimedia.org/wikipedia/he/thumb/e/e3/Feyenoord_logo.svg/250px-Feyenoord_logo.svg.png",
  "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/FC_Internazionale_Milano_2021.svg/1280px-FC_Internazionale_Milano_2021.svg.png",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN3LaRdZFZI01ZHXQDbFOOthZekK1DgyCadQ&s",
  "https://upload.wikimedia.org/wikipedia/he/e/e4/Venezia_FC_Logo.png",
  "https://upload.wikimedia.org/wikipedia/he/a/a3/US_Sassuolo_Calcio.svg",
  "https://upload.wikimedia.org/wikipedia/he/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/1280px-Brighton_%26_Hove_Albion_logo.svg.png",
  "https://upload.wikimedia.org/wikipedia/commons/d/da/BesiktasJK-Logo.svg",
  "https://upload.wikimedia.org/wikipedia/he/thumb/e/eb/Fulham_FC_%28shield%29.svg/960px-Fulham_FC_%28shield%29.svg.png",
  "https://apinew.goalzo.co.il/admin/images/teams-logos/italy-napoli.png",
  "https://upload.wikimedia.org/wikipedia/he/1/13/Real_betis_logo.svg",
  "https://upload.wikimedia.org/wikipedia/he/b/b4/Tottenham_Hotspur.svg",
  "https://upload.wikimedia.org/wikipedia/he/0/05/PSV_Eindhoven.svg",
  "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Olympique_Marseille_logo.svg/250px-Olympique_Marseille_logo.svg.png",
  "https://upload.wikimedia.org/wikipedia/he/5/57/Auxerre.gif",
  "https://images.one.co.il/images/msites/leagues/logos150/b63fc6c7cdf334cc5d5f050c4598b3ed.png",
  "https://images.one.co.il/images/msites/leagues/logos150/9b10e0e39f688d5f71cd1ab8402e60cd.png",
  "https://images.one.co.il/images/msites/leagues/logos150/0f62c5e908bdd94233e8359ef13ffaa4.png",
  "https://images.one.co.il/images/msites/leagues/logos150/c6b4a3e1f3ac2633bc9bde643c6c8feb.png",
];

const people = [
  "https://ynet-pic1.yit.co.il/picserver5/crop_images/2014/07/03/pp5432189/pp5432189_0_0_650_975_0_large.jpg",
 "https://upload.wikimedia.org/wikipedia/commons/7/74/Benjamin_Netanyahu%2C_February_2023.jpg",
  "https://upload.wikimedia.org/wikipedia/commons/f/f4/USAFA_Hosts_Elon_Musk_%28Image_1_of_17%29_%28cropped%29.jpg",
  "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg/250px-Jeff_Bezos_at_Amazon_Spheres_Grand_Opening_in_Seattle_-_2018_%2839074799225%29_%28cropped%29.jpg",
 "https://www.israelhayom.co.il/wp-content/uploads/2022/04/19/15350361482097_b-scaled.jpg",
 "https://sport1images.maariv.co.il/image/upload/f_auto,fl_lossy,c_thumb,g_north,w_728,h_441/1248079?t=1",
 "https://www.c14.co.il/wp-content/uploads/2025/03/shutterstock_2115245072-scaled.jpg",
"https://img.allfootballapp.com/www/M00/3A/0B/720x-/-/-/CgAGVWOfiSyAZXSJAAKuEDFsb78113.jpg",
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWAXqFGfrMKp_MJSVL5inJ-QFS8R17wraJJg&s",
"https://sport1images.maariv.co.il/image/upload/f_auto,fl_lossy,c_thumb,g_north,w_1200,h_630/1178161",
"https://forbes.co.il/wp-content/uploads/2022/10/shutterstock-21952131992.jpg",
"https://sport1images.maariv.co.il/image/upload/f_auto,fl_lossy/t_ArticleControlTransformaionFaceDetect/674967",
"https://www.sport5.co.il/Sip_Storage/FILES/1/1458321.jpg",
"https://sport1images.maariv.co.il/image/upload/f_auto,fl_lossy/t_ArticleControlTransformaionFaceDetect/671965",
"https://www.israelhayom.co.il/wp-content/uploads/2021/10/25/New_Hornets_Nets_Basketball_77890-931db-1024x684.jpg",
"https://www.amigo.co.il/wp-content/uploads/2017/11/steph-curry-feature.jpg",
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPKLXgk0EiGuXMexce0jQNa5UNFbJKWm3KcQ&s",
"https://www.sport5.co.il/Sip_Storage/FILES/7/size475x318/809587.jpg",
"https://gilshalevwrites.com/wp-content/uploads/2024/07/dccormier.jpg",
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3mLynudFiZUhZEroEozzR0OVhm_8weBIR0A&s",
"https://images1.ynet.co.il/PicServer5/2017/01/16/7520999/GettyImages-617820852.jpg",
"https://www.reali.co.il/wp-content/uploads/2018/08/shutterstock_774735439.jpg",
"https://i.guim.co.uk/img/media/7177a3c71b2cfb1b56a0213fd2f91462221caf70/0_128_3456_2073/master/3456.jpg?width=465&dpr=1&s=none&crop=5%3A4",
"https://upload.wikimedia.org/wikipedia/commons/c/c0/Gal_Gadot_at_the_2018_Comic-Con_International_13_%28cropped%29.jpg",
"https://images.maariv.co.il/image/upload/f_auto,fl_lossy/t_ArticleControlTransformaionFaceDetect/413155",
"https://www.israelhayom.co.il/wp-content/uploads/2025/06/10/10/New_ALAN3872-960x640.jpg",
"https://basket.co.il/pics/2025-2026/%D7%A9%D7%95%D7%A0%D7%95%D7%AA/sanogo.png",
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtxKr1raeVQuOGy_pgGBc3l4KBzPT_oWu1UA&s",
"https://images.globes.co.il/images/NewGlobes/big_image_800/2015/RTR35EY7-800.jpg",
];

const animals = [
  "https://static.vecteezy.com/system/resources/thumbnails/026/525/162/small/lion-animal-isolated-photo.jpg",
  "https://www.amsterdam.org.il/Photos/Holland/Giant-Panda-Bear.jpg",
  "https://chowchow.co.il/wp-content/uploads/2020/08/ferret.jpg",
  "https://upload.wikimedia.org/wikipedia/commons/8/84/Humpback_whale_noaa.jpg",
  "https://midbarium.co.il/wp-content/uploads/2023/06/%D7%92%D7%99%D7%A8%D7%A4%D7%94.jpg",
  "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Mouse_white_background.jpg/250px-Mouse_white_background.jpg",
  "https://www.teva.org.il/app/uploads/2021/10/%D7%90%D7%99%D7%AA%D7%9F-%D7%A7%D7%90%D7%95%D7%A4%D7%9E%D7%9F-%D7%93%D7%95%D7%9B%D7%99%D7%A4%D7%AA.jpg",
  "https://www.teva.org.il/app/uploads/2024/03/shutterstock_93360157-1-scaled.jpeg",
  "https://www.goeco.co.il/wp-content/uploads/2017/06/6282.jpg",
  "https://simplesteps.co/images/animals/kengeru.jpg",
  "https://nationalgeographic.co.il/wp-content/uploads/2025/04/%D7%9E%D7%99%D7%99%D7%A0%D7%94-%D7%9E%D7%A6%D7%95%D7%99%D7%94.jpg",
  "https://res.cloudinary.com/globes/image/upload/t_550X400/v1684924543/direct/shutterstock_2205677135_poczri.jpg",
  "https://res.cloudinary.com/globes/image/upload/t_550X400/v1684924544/direct/shutterstock_324845348_vdhyha.jpg",
  "https://cdn.babamail.co.il/Images/2014/11/9/bdd3b640-8f07-437b-a40b-cd164857e989.jpg",
];